### ISSUE TITLE
[RFC] Further improvements for spec runner (and feedback)

### ISSUE THREAD

**Issue by mgreter** [sass/sass-spec#845] opened 2016-04-23 08:08 UTC
Mostly targeted towards the recent work done by @chriseppstein.

1) thanks for the work, I like that someone is taking care of sass-spec
2) don't take this feedback too serious, just wanted to give my 2 cents
3) also in regard that perl-libsass (and node-sass) have their own spec runners

- I like the approach with the `options.yml` in general
- I do not like the split of different out styles on the first glance
  - it increased [size considerabely] [1] for perl dist (1.3M to 2.1M)
  - not sure if this is fully because of the split, but I guess so
  - counter arg: it's the most common "multiple" option; in old implementation ...
  - ... each expected output was optional (equivalent to the directories now)
  - still after rethinking it for some time, I think that design made sense.
- `--run-todo` does not make much sense to me in the current state
  - I don't see a use case where runner should abort if todo test does not pass
  - Only thing that comes closed would be with a very specific filter argument
  - I added the behavior I would expect under option `--probe-todo`
  - Disclaimer: I am not sure if exit code signals error for `--run-todo`
  - [ ] I propse to consider to replace `--run-todo` with the new behavior.
- [x] Message for `--skip` confuses me (maybe option name is too generic?)
- I have no real clue what the `migrate` option does (just glanced the code)
- I like the interactive mode (altough I just barely used it for adding `--probe-todo`)
- [x] A bit more documentation would be nice (IMO best with some real walk-throughs)
- parallel mode would be nice (in perl-libsass I opted for distinct output files for each test)
  - I tried with stdin, stderr redirect, but it's doomed with fork; and threads are not so portable
  - so I just assign unqiue files for stdin, stderr and parallelize the commands of sassc
  - this way I just need to know the the exit status, which works also well on windows
  - pretty sure ruby will have the same problems, so this has proven to work in perl

Further ideas to improve here:

- Add some workflow to create (and activate) todo spec tests (incl. commits and pushes). I already added a batch file I used to create the missing spec tests under tools folder. I just added it so others may use it if it works for them (and also for myself), but no support is given. Having this workflow automated could help to encourage users to submit their spec tests on their own. In the long shot the spec runner could therefore act as an official bug report tool. I guess I don't have to mention this also allows to catch a lot of possible human errors.

Of course I do not really like that I probably have to update the spec runner in perl-libsass :wink: For now I just exclude offending directories by hardcoding them. I know it's rather optional to have this included in perl-libsass, but the nice thing is that this gets us [automated coverage accross] [2] a bigger set of systems than with our CI.

Really looking forward to see sass-spec evolve with ruby sass on board!
I marked three items above which I would consider as DoD for this issue.

[1]: http://www.cpan.org/authors/id/O/OC/OCBNET/
[2]: http://matrix.cpantesters.org/?dist=CSS-Sass

**Comment by chriseppstein** [comment] 2016-04-25 21:30
@mgreter ok that's a lot of different points, I'll try to address them all but I'm worried this will become incoherent so it may be better to split this into different issues if we find ourselves getting confused.

> I do not like the split of different out styles on the first glance ... still after rethinking it for some time, I think that design made sense.

I have to disagree. Here's some of my reasons:

1. output formats are not part of the sass language specification. I know that libSass has set a goal to implement all of them, but we simply don't care whether any particular sass implementation has output differences. I get that some implementations want to test whitespace, and that's optional for any implementation.
2.output formats were not being tested systematically in sass-spec, but instead just hoping that if we run enough code through them then we'd find output format differences. I moved these tests into their own subdirectories so that we would maintain test coverage, but all this duplication is just a step towards my goal of getting rid of those tests and replacing them with tests that specifically test formats in a directed way.
3. there was no way to attach metadata (`options.yml`) in a output format specific way that was also implementation dependent. In other words, there was no way to mark a single output format as todo for just libsass. You could mark an output file as `.skip` but this caused it to be skipped for both ruby and libsass.
4. Running sass-spec tests against the same directory in the same run meant that interactive mode got really complicated because we were running every output format in it's own instance of a test case and so there wasn't a good way to manage "how should I fix this broken test" when there's all these different competing diffs that you'd need to try to make sense of.

I will address other points in a subsequent reply.

**Comment by chriseppstein** [comment] 2016-04-25 21:36
```
- `--run-todo` does not make much sense to me in the current state
  - I don't see a use case where runner should abort if todo test does not pass
  - Only thing that comes closed would be with a very specific filter argument
  - I added the behavior I would expect under option `--probe-todo`
  - Disclaimer: I am not sure if exit code signals error for `--run-todo`
  - I propose to consider to replace `--run-todo` with the new behavior.
```

I'm pretty confused here. The `--run-todo` option runs todo tests. The runner doesn't abort if it fails; todo tests that don't pass are marked a failing tests. This is useful in development so you can see what's failing and fix it. The `--probe-todo` option is good. I touched it up on master so that when the todo test fails it's marked as a skip so that the result is still a "green" status. But seeing which todo tests are failing and what their failure is seems like a generally good feature to have so I don't agree that we should replace `--run-todo` with it. Anyways, In ruby sass we don't be using the todo functionality much so I will not be obstinate about TODO features in sass-spec except to assert that we should not make things too implementation specific like they were before I did my work.

**Comment by chriseppstein** [comment] 2016-04-25 21:51
>  Message for --skip confuses me (maybe option name is too generic?)

Actually, this option doesn't do anything anymore; we should remove it. A failing test is a failing test and there's no provision in sass spec to hide them now except by marking them as todo for the current implementation.

> I have no real clue what the migrate option does (just glanced the code)

Hmm. I guess I didn't explain it well in the help: "Copy tests that fail and make them pass for the current version". The migrate option is this:

1. make a copy of the current test named "<folder>-<current_version>"
2. mark the original test as having an `end_version` as the version that comes before the version being tested right now.
3. set the copy as having a `start_version` as the version being tested right now.
4. regenerate the output for the new test so that it passes.

> I like the interactive mode (although I just barely used it for adding --probe-todo)

Yay! This was the feature I set out to build from very early on, a lot of the refactoring I did was simply to pave the way for this.

> A bit more documentation would be nice (IMO best with some real walk-throughs)

I agree. I will do this.

> parallel mode would be nice (in perl-libsass I opted for distinct output files for each test)

I agree. I want to enable that. We have to fix this bug in ruby sass first: https://github.com/sass/sass/issues/2032

> Add some workflow to create (and activate) todo spec tests (incl. commits and pushes). I already added a batch file I used to create the missing spec tests under tools folder. I just added it so others may use it if it works for them (and also for myself), but no support is given. Having this workflow automated could help to encourage users to submit their spec tests on their own. In the long shot the spec runner could therefore act as an official bug report tool. I guess I don't have to mention this also allows to catch a lot of possible human errors.

I like the idea of creating an interactive tool for writing new specs. Currently the process is:
1. Add an `input.s[ac]ss` file in a folder.
2. Optionally, annotate it with `sass-spec.rb annotate ... <path_to_folder>`
3. Run `sass-spec.rb -g <path_to_folder>`
4. commit and send PR

This can be streamlined, but it also not very onerous.

**Comment by saper** [comment] 2016-04-25 22:58
One thing that always annoyed me is that sass-spec.rb -g <path_to_folder/input.scss> didn't work before, now it works - thank you!

**Comment by mgreter** [comment] 2016-04-25 23:16
As I said, don't take my feedback too serious. I am merely writing down what pops to my head since I hope it might be helpfull to see my thought process here (and I hope in that sense that it's helpfull, otherwise just tell me and I will stop doing that). And yes feel free to fork off different tickets for feature request etc. as you see fit.

So let me give an answer to your points above:

1) I guess this comes back to something I wrote in another post: I think it would make sense to split the spec tests into two different repos at some point. One that is a well defined spec test set for the language itself; and I agree this does only need different output formats for those tests that exactly work out the specified differences. On the other hand for an implementor it can be usefull to have a huge amount of different tests, even if the chances are very high they test the same behavior. I think it still has a big benefit that way, as it tends to reveal those subtle differences. Remind that I pretty much re-implemented the whole rendering for the output styles, and in that process it was invaluable to have all the different test cases (I basically had to figure out these patterns myself in the first place and we also found a [few] [1] inconsistencies on the ruby sass side IMHO). So to me it's more like we are talking about two different kind of spec tests suites and I guess your pointing in the same direction with "I get that some implementations want to test whitespace". In my own experience the progress libsass made here helps a lot when you need to diff ruby sass output to libsass to verify if you can upgrade a code base to use libsass (one more space correctly could mean hundreds of less lines you need to manualy compare).

To expand a little on this topic here: In the beginning I myself wanted to ignore pretty much all of the white-space issues. AFAIR @xzyfer wanted to be more strict about these, so our current policy is pretty much every space that is not exactly as ruby sass is considered a bug (although lowest priority, with the exception of single/double linefeeds). This was not very easy on my part, because it often meant a lot of refactoring for a small gain in the end. But overall it paid out, as it often pointed to a deeper issue (best example is static parsed values vs. evaluated values, which seem to exhibit the most prominent differencies on various output modes). The problem for me here is where to draw the line, because in that sense I would also consider https://github.com/sass/libsass/issues/1730 not to be a bug.

2) I agree the old way was inflexible and pretty much just hacked together to support the progress of libsass where needed. Not much thought was put into it, so as I pointed out earlier "I like the approach with the options.yml in general". As you probably have seen I added a baby version of that appraoch to set the precision option, so this is exactly the direction I would have moved to. Only I didn't want to include the output style in there, since it doesn't yet make much sense in the current state of sass-spec. I really hope you/we can get sass spec to a state it represents the authority of the sass language in a minimal set. But I just know that this is really really a lot lot of work :wine_glass: AFAIK not even CSS has pulled that one off (CSS3 Acid test is good but not complete, mozilla also gave it more than one shot). But to stay positive, we probably only have to do it for the scss part (and leave the rest for css). As a side note, in the "progress indicator", I would probably use `-`  instead of `S` to stand out better from `F` (or `!`) for failures (`.....SS..SSFSSS.....` vs `.....--..--F---...`). But that's just a minor console UX thing :)

I may was wrong about the assumption that `--run-todo` would exit with a fail state in the end. Not sure if I actually tested it, but if you say it does not, I guess I didn't. I think you understood what I want for CI to show up. I don't want to see the diffs for expectedly failing todo test, I only want to see a list of the ones that do unexpectedly pass. It would make spotting real failures in CI logs more difficult, beside repeatedly printing them in every CI run.

Lastly for the automated spec test creation: Did you take a look at the [batch file `en_libsass_todo.cmd`] [2] I added? The workflow with it is (mileage may vary!):

- create #nr.scss (i.e. `845.scss`) -> no sass support for now
- execute `gen_libsass_todo 845 [mgreter]` (second argument optional)
- then it will (copied from the minimal readme)
- create folder and necessary files
- call spec runner to nuke the test
- add files to git and create commit
- optionally push to the given remote

I created all the missing spec that were added recently test this way. I only had to go to the github page and click the "create pull request" button for each branch. I probably will also add a counter part for activated todo specs. But I should point out that a lot can go wrong with this approach too, since it has to create a new branch in your local repository (what happens if it's dirty? etc.). So these simple batch scripts do need sometimes some attendance by the dev, whereas a solution via ruby could probably handle many more use cases more easily. But also to repeat, this is really a long shot idea. Nothing I write here is a must or any action must be taken immediately. Just wanted to lay out my thoughts before you, so you take better guesses than I was able to :smile: 

Just to repeat the point that this is really just meant as feedback and food for the brain. You don't need to respond to each paragraph. I'm very glad if someone else could take the lead on sass-spec, specially someone who knows the original specs as well as you do! It's just that sass-spec is an integral part of libsass CI now, and I would be a bit sad if we loose all those "strict" tests we currently pass. So the have a clear final statement: I would be more than happy to include only a minimal set of spec-test in perl-libsass distribution (+95% of size are spec test now), but I don't really want to stop testing libsass CI against the "full" spec test (which is the argument to split it into two repos).

Sorry for it beeing that long of an answer, it's too big to comb over it again, so I'll just post as is!

Thanks again for your initiative and to success :smile: 

[1]: https://github.com/sass/libsass/issues/1612
[2]: https://github.com/sass/sass-spec/tree/master/tools

**Comment by chriseppstein** [comment] 2016-04-26 18:39
I am very much on board with the idea of splitting the spec into two or more sets of tests. In an ongoing way, @nex3 and myself will be writing specs that must pass for an implementation to call itself an implementation of "Sass at version X.Y".

There are other things that an implementation may want to test using the sass-spec utility, one of which is output styles, in order to meet their specific goals. We are totally cool with those being in a separate directory in sass-spec or even moving such specs into the specific implementation's repo. The sass-spec.rb script will happily test a conforming directory that is not our official spec directory.

I've been trying to make step-wise improvements while also maintaining the existing tests for libsass. I want to start organizing and re-writing the specs themselves, but it's not clear how much value that offers vs. me putting that same effort into working on new versions of sass.

> But overall it paid out, as it often pointed to a deeper issue (best example is static parsed values vs. evaluated values

If we had been writing sass specs for a long time there would have been specific specs that would have tested the static parsing semantics. I'm not denying that these tests added value, but ultimately, now that @nex3 and I are working together with you on these specs, I hope that our clarity around how the language is built and should work will translate to specs that are much more targeted and fail predictably; something that the black-box approach isn't as good at.

>  I would probably use - instead of S

I just made this change in 94b11e366af6aeaf2e5d0dd2a319c004ff99b5c0

FWIW, I'm happy to take co-ownership of sass-spec, it's something I've wanted to help out with for a long time but have only recently found the time and motivation to do. I think I'm uniquely situated to help coordinate and decide what should be a "spec" and what shouldn't etc. But I think this project needs contributors from every major implementation of Sass.

> I maybe was wrong about the assumption that --run-todo would exit with a fail state in the end.

Not wrong. If you run TODOs and one of them fails, it will result in a non-zero exit status. When you said "abort", I thought you meant that it would stop running further tests. I think `--probe-todo` semantics work better for running specs in CI, but that doesn't mean there's not a use case for failing todos in during development. So, I think the two modes can happily co-exist.

> the argument to split it into two repos

The downside to splitting into two repos is that when future versions break existing specs, we won't be able to migrate them for you and you'll need to check in with us to see if it's a regression or if it's intentional.

**Comment by chriseppstein** [comment] 2016-04-26 18:49
I've removed the `--skip` option in a9dea7aea4316f2280151d3386b4b7babb08c07b.

**Comment by chriseppstein** [comment] 2016-04-26 20:13
Docs updated in 33a48ce3178d387107a725adbb83eeed6605c5f8.

**Comment by chriseppstein** [comment] 2016-04-26 20:15
> it increased size considerably for perl dist (1.3M to 2.1M)

I'm not sure why you're distributing sass-spec with the perl wrapper, but I suggest pairing down the specs that you include to something more simple. Maybe we can organize the specs or annotate them such that some specs are marked as "smoke" specs that provide a broad level of testing without as much depth but run a lot faster.

**Comment by chriseppstein** [comment] 2016-04-26 20:17
> I propose to consider to replace --run-todo with the new behavior.

I think we should keep both and that libsass should use `--probe-todo` in CI instead of `--run-todo` (if it's not already)

I'm closing this as it seems all the key issues have been discussed and addressed were applicable. Reopen if you disagree.

**Closed by chriseppstein** 2016-04-26 20:17 UTC
