### ISSUE TITLE
The interactive TS runner breaks CR line endings

### ISSUE THREAD

**Issue by stof** [sass/sass-spec#1643] opened 2021-05-03 23:50 UTC
See `spec/css/comment.hrx` which contains some CR line endings. When running the interactive mode, they get replaced.

**Comment by Awjin** [comment] 2022-02-18 22:34
I can replicate this for form feeds, but having trouble replicating CR. Could you describe the behavior that you're seeing?

**Comment by stof** [comment] 2022-02-26 00:10
if you run the runner in interactive mode, with a change performed on that file (so that the interactive mode updates the file), newline characters were being replaced IIRC. But I haven't tried to reproduce it now.

**Comment by nex3** [comment] 2022-03-18 20:55
I'm unable to reproduce this with any of those test cases (on Linux). I tried editing the input files, running in interactive mode, and updating the outputs and the inputs continued to have the appropriate line ending characters.

I'll close this out for now, but feel free to reopen with more detailed reproduction steps if you have them.

**Closed by nex3** 2022-03-18 20:55 UTC
Labels: bug
