### ISSUE TITLE
Change format of tests

### ISSUE THREAD

**Issue by michaek** [sass/sass-spec#46] opened 2014-09-18 13:25 UTC
Currently, every test requires its own directory, with two specifically named files: input.scss and expected_output.css. Because there are a lot of files, this makes reading through the tests and even grouping contextually related tests difficult.

I'd like to suggest some changes that would allow us to name files after their tests, and express multiple assertions per file. We could take our current [extend-tests/001_test_basic](https://github.com/sass/sass-spec/tree/master/spec/extend-tests/001_test_basic) and put the following in `extend-tests/basic.scss`:

    /*
    .foo, .bar {
      a: b; }
    */

    .foo {a: b}
    .bar {@extend .foo}

Because block comments are preserved in the output, we can compare the output from our scss to the contents of the comment block after compiling. It would be pretty easy to include multiple scss/comment pairs:

    /*
    .foo, .bar {
      a: b; }
    */

    .foo {a: b;}
    .bar {@extend .foo;}

    /*
    .foo, .bar {
      a: b; }
    */

    .bar {@extend .foo;}
    .foo {a: b;}

I think this would aid comprehensibility, and keep the parts of sass-spec that were derived from Ruby Sass's test cases closer to the structure of those tests. Thoughts?

**Comment by saper** [comment] 2015-09-21 08:47
I am late to the party and from the view of the newcomer I'd like to strongly support status quo.
Why?

Over the past two days, with practically zero Ruby experience, I was able to contribute larger things like #494 or tiny like #503. I really needed 15 minutes to get some little changes working and Ruby coding started to fell natural - because our code base is so tiny and easy to understand.

Plugging additional stuff like `error` or `status`, while maybe not winning beauty contests, proved simple and quickly lead to practical results like #502, which demonstrated few regressions or unfixed bugs in libsass.

Of course, one can argue that if we switch to JSON/YAML/whatever the code grows only by one or two lines where the file is read which just (de)serialize the file into ruby objects. But here is why I think this is not good:

Already in at least two cases (out of 14 I was working on) when testing for error output I have deployed **hex dump** to figure out WHY the messages returned by libsass and ruby sass differ. Was it additional space? A quote I am missing? Was one giving CR LF and the other LF? Tabs vs. spaces?

In those cases I just launch hexdump or some binary diff tools - call me weird. And I need plain old text files for that.

Stuffing it into JSON/YAML/whatever will cause the need to quote stuff to fit in the file and although I think the tools to do that are robust in the mean time I don't want to do an extra `jq` run just to extract the plain text value I want to have a detailed look at.

And things like #1 an be fixed with a simple additional file that lists per-spec keywords, which are interpreted by Ruby classes (something like annotations). I'd go for the simplest words, even without parameters, like `since_3.4` or whatever. And those rules should only feed the decision whether to skip or not the test.

**Comment by chriseppstein** [comment] 2016-04-26 20:35
There is now a `options.yaml` file that stores metadata on a per-folder basis. These options are inherited by subdirectories. multiple files are being used to store expected output, but it's exceedingly easy now to generate and update these files using the `sass-spec.rb --interactive` mode or by using the `--generate` or `--migrate` options.

**Closed by chriseppstein** 2016-04-26 20:35 UTC
